### ISSUE TITLE
TODO: 0.0.7

### ISSUE THREAD

**Issue by ghost** [Dextroz/virustotal-python#14]
# 0.0.7 TODO List

- [x] Add Tests. Most likely using Pytest.
- [x] Fix #13.
- [x] Bump version numbers.
- [x] Update changelog.
- [x] Update dependencies; if available. (Requirements.txt)
- [x] Altered `/url/report` `scan` parameter is now `type(int)`.

**Comment by ghost** [comment]
#15
