### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by dbrennand** [Dextroz/virustotal-python#32]
# 1.0.0

Work in progress in branch [1.0.0](https://github.com/dbrennand/virustotal-python/tree/1.0.0).

This release will contain breaking changes to the library.

## Task List

- [x] Allow use of int 2 and 3 for `API_VERSION`.
- [x] Migrate away from Pipenv.
- [x] Drop support for `COMPATIBILITY_ENABLED` (breaking change).
- [x] Default to VirusTotal API version 3 (breaking change).
- [x] #31 
- [x] Check examples.
- [x] Automate library tests using GitHub actions.
- [x] Automate library publishing using GitHub actions.
- [x] Update README.md.
- [x] Update changelog in README.md.

`Updated 27/03/22`

**Comment by aserputov** [comment]
Hey, @dbrennand I would like to work on this issue. Could you please assign me ?

**Comment by dbrennand** [comment]
> Hey, @dbrennand I would like to work on this issue. Could you please assign me ?
> 
> 

Hi @aserputov 👋🏻 

Awesome! I've actually completed the task to migrate away from Pipenv and use Poetry. I just haven't pushed those commits yet. Hopefully I can do this sometime soon so we could look at automating tests and publishing using a GitHub action such as: https://github.com/abatilo/actions-poetry

Also, I've pushed some commits for the Google docstring formats in branch v0.2.0. Specifically for virustotal.py.

I wasn't planning on changing any of the lib's functionality so if you're experienced with writing some unit tests with Pytest then that would help so much!

Otherwise, I'll push the poetry commits ASAP so you could start working on the GitHub actions bit 🙂

Let me know what you're comfortable doing 👍🏻🙂

**Comment by aserputov** [comment]
@dbrennand hey, I want to try working with Pytest.
